packages:
  - "apps/*"
  - "packages/*"

# Define shared dependency versions
catalog:
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.81.5

  react-native-paper: ^5.14.5
  react-native-safe-area-context: ~5.6.2

  # Dev dependencies
  "@types/react": ~19.1.10
  "@types/react-dom": ~19.1.10
